/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamer.fish;

import javax.swing.JButton;

/**
 *
 * @author andre
 */
public class Gameplay extends javax.swing.JFrame {

    /**
     * Creates new form Gameplay
     */
    JButton[][] playerHand = new JButton[3][13];
    public Gameplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuButton = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        button13 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button15 = new javax.swing.JButton();
        button16 = new javax.swing.JButton();
        button17 = new javax.swing.JButton();
        button18 = new javax.swing.JButton();
        button19 = new javax.swing.JButton();
        button20 = new javax.swing.JButton();
        buton21 = new javax.swing.JButton();
        button22 = new javax.swing.JButton();
        button23 = new javax.swing.JButton();
        button24 = new javax.swing.JButton();
        button25 = new javax.swing.JButton();
        button26 = new javax.swing.JButton();
        button14 = new javax.swing.JButton();
        button28 = new javax.swing.JButton();
        button29 = new javax.swing.JButton();
        button30 = new javax.swing.JButton();
        button31 = new javax.swing.JButton();
        button32 = new javax.swing.JButton();
        button33 = new javax.swing.JButton();
        button34 = new javax.swing.JButton();
        button35 = new javax.swing.JButton();
        button36 = new javax.swing.JButton();
        button37 = new javax.swing.JButton();
        button38 = new javax.swing.JButton();
        button39 = new javax.swing.JButton();
        button27 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        tableBackground = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuButton.setText("Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 60));

        button2.setMaximumSize(new java.awt.Dimension(127, 180));
        button2.setMinimumSize(new java.awt.Dimension(127, 180));
        button2.setPreferredSize(new java.awt.Dimension(127, 180));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 790, -1, -1));

        button3.setMaximumSize(new java.awt.Dimension(127, 180));
        button3.setMinimumSize(new java.awt.Dimension(127, 180));
        button3.setPreferredSize(new java.awt.Dimension(127, 180));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 790, -1, -1));

        button4.setMaximumSize(new java.awt.Dimension(127, 180));
        button4.setMinimumSize(new java.awt.Dimension(127, 180));
        button4.setPreferredSize(new java.awt.Dimension(127, 180));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 790, -1, -1));

        button5.setMaximumSize(new java.awt.Dimension(127, 180));
        button5.setMinimumSize(new java.awt.Dimension(127, 180));
        button5.setPreferredSize(new java.awt.Dimension(127, 180));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 790, -1, -1));

        button6.setMaximumSize(new java.awt.Dimension(127, 180));
        button6.setMinimumSize(new java.awt.Dimension(127, 180));
        button6.setPreferredSize(new java.awt.Dimension(127, 180));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 790, -1, -1));

        button7.setMaximumSize(new java.awt.Dimension(127, 180));
        button7.setMinimumSize(new java.awt.Dimension(127, 180));
        button7.setPreferredSize(new java.awt.Dimension(127, 180));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 790, -1, -1));

        button8.setMaximumSize(new java.awt.Dimension(127, 180));
        button8.setMinimumSize(new java.awt.Dimension(127, 180));
        button8.setPreferredSize(new java.awt.Dimension(127, 180));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 790, -1, -1));

        button9.setMaximumSize(new java.awt.Dimension(127, 180));
        button9.setMinimumSize(new java.awt.Dimension(127, 180));
        button9.setPreferredSize(new java.awt.Dimension(127, 180));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 790, -1, -1));

        button10.setMaximumSize(new java.awt.Dimension(127, 180));
        button10.setMinimumSize(new java.awt.Dimension(127, 180));
        button10.setPreferredSize(new java.awt.Dimension(127, 180));
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        getContentPane().add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 790, -1, -1));

        button11.setMaximumSize(new java.awt.Dimension(127, 180));
        button11.setMinimumSize(new java.awt.Dimension(127, 180));
        button11.setPreferredSize(new java.awt.Dimension(127, 180));
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        getContentPane().add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 790, -1, -1));

        button12.setMaximumSize(new java.awt.Dimension(127, 180));
        button12.setMinimumSize(new java.awt.Dimension(127, 180));
        button12.setPreferredSize(new java.awt.Dimension(127, 180));
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        getContentPane().add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 790, -1, -1));

        button13.setMaximumSize(new java.awt.Dimension(127, 180));
        button13.setMinimumSize(new java.awt.Dimension(127, 180));
        button13.setPreferredSize(new java.awt.Dimension(127, 180));
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        getContentPane().add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 790, -1, -1));

        button1.setMaximumSize(new java.awt.Dimension(127, 180));
        button1.setMinimumSize(new java.awt.Dimension(127, 180));
        button1.setPreferredSize(new java.awt.Dimension(127, 180));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 790, -1, -1));

        button15.setMaximumSize(new java.awt.Dimension(127, 180));
        button15.setMinimumSize(new java.awt.Dimension(127, 180));
        button15.setPreferredSize(new java.awt.Dimension(127, 180));
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        getContentPane().add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 740, -1, -1));

        button16.setMaximumSize(new java.awt.Dimension(127, 180));
        button16.setMinimumSize(new java.awt.Dimension(127, 180));
        button16.setPreferredSize(new java.awt.Dimension(127, 180));
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        getContentPane().add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 740, -1, -1));

        button17.setMaximumSize(new java.awt.Dimension(127, 180));
        button17.setMinimumSize(new java.awt.Dimension(127, 180));
        button17.setPreferredSize(new java.awt.Dimension(127, 180));
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });
        getContentPane().add(button17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 740, -1, -1));

        button18.setMaximumSize(new java.awt.Dimension(127, 180));
        button18.setMinimumSize(new java.awt.Dimension(127, 180));
        button18.setPreferredSize(new java.awt.Dimension(127, 180));
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        getContentPane().add(button18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 740, -1, -1));

        button19.setMaximumSize(new java.awt.Dimension(127, 180));
        button19.setMinimumSize(new java.awt.Dimension(127, 180));
        button19.setPreferredSize(new java.awt.Dimension(127, 180));
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        getContentPane().add(button19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 740, -1, -1));

        button20.setMaximumSize(new java.awt.Dimension(127, 180));
        button20.setMinimumSize(new java.awt.Dimension(127, 180));
        button20.setPreferredSize(new java.awt.Dimension(127, 180));
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        getContentPane().add(button20, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 740, -1, -1));

        buton21.setMaximumSize(new java.awt.Dimension(127, 180));
        buton21.setMinimumSize(new java.awt.Dimension(127, 180));
        buton21.setPreferredSize(new java.awt.Dimension(127, 180));
        buton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton21ActionPerformed(evt);
            }
        });
        getContentPane().add(buton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 740, -1, -1));

        button22.setMaximumSize(new java.awt.Dimension(127, 180));
        button22.setMinimumSize(new java.awt.Dimension(127, 180));
        button22.setPreferredSize(new java.awt.Dimension(127, 180));
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        getContentPane().add(button22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 740, -1, -1));

        button23.setMaximumSize(new java.awt.Dimension(127, 180));
        button23.setMinimumSize(new java.awt.Dimension(127, 180));
        button23.setPreferredSize(new java.awt.Dimension(127, 180));
        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });
        getContentPane().add(button23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 740, -1, -1));

        button24.setMaximumSize(new java.awt.Dimension(127, 180));
        button24.setMinimumSize(new java.awt.Dimension(127, 180));
        button24.setPreferredSize(new java.awt.Dimension(127, 180));
        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });
        getContentPane().add(button24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 740, -1, -1));

        button25.setMaximumSize(new java.awt.Dimension(127, 180));
        button25.setMinimumSize(new java.awt.Dimension(127, 180));
        button25.setPreferredSize(new java.awt.Dimension(127, 180));
        button25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button25ActionPerformed(evt);
            }
        });
        getContentPane().add(button25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 740, -1, -1));

        button26.setMaximumSize(new java.awt.Dimension(127, 180));
        button26.setMinimumSize(new java.awt.Dimension(127, 180));
        button26.setPreferredSize(new java.awt.Dimension(127, 180));
        button26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button26ActionPerformed(evt);
            }
        });
        getContentPane().add(button26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 740, -1, -1));

        button14.setMaximumSize(new java.awt.Dimension(127, 180));
        button14.setMinimumSize(new java.awt.Dimension(127, 180));
        button14.setPreferredSize(new java.awt.Dimension(127, 180));
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        getContentPane().add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 740, -1, -1));

        button28.setMaximumSize(new java.awt.Dimension(127, 180));
        button28.setMinimumSize(new java.awt.Dimension(127, 180));
        button28.setPreferredSize(new java.awt.Dimension(127, 180));
        button28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button28ActionPerformed(evt);
            }
        });
        getContentPane().add(button28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, -1, -1));

        button29.setMaximumSize(new java.awt.Dimension(127, 180));
        button29.setMinimumSize(new java.awt.Dimension(127, 180));
        button29.setPreferredSize(new java.awt.Dimension(127, 180));
        button29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button29ActionPerformed(evt);
            }
        });
        getContentPane().add(button29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, -1, -1));

        button30.setMaximumSize(new java.awt.Dimension(127, 180));
        button30.setMinimumSize(new java.awt.Dimension(127, 180));
        button30.setPreferredSize(new java.awt.Dimension(127, 180));
        button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button30ActionPerformed(evt);
            }
        });
        getContentPane().add(button30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 680, -1, -1));

        button31.setMaximumSize(new java.awt.Dimension(127, 180));
        button31.setMinimumSize(new java.awt.Dimension(127, 180));
        button31.setPreferredSize(new java.awt.Dimension(127, 180));
        button31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button31ActionPerformed(evt);
            }
        });
        getContentPane().add(button31, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, -1, -1));

        button32.setMaximumSize(new java.awt.Dimension(127, 180));
        button32.setMinimumSize(new java.awt.Dimension(127, 180));
        button32.setPreferredSize(new java.awt.Dimension(127, 180));
        button32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button32ActionPerformed(evt);
            }
        });
        getContentPane().add(button32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 680, -1, -1));

        button33.setMaximumSize(new java.awt.Dimension(127, 180));
        button33.setMinimumSize(new java.awt.Dimension(127, 180));
        button33.setPreferredSize(new java.awt.Dimension(127, 180));
        button33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button33ActionPerformed(evt);
            }
        });
        getContentPane().add(button33, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 680, -1, -1));

        button34.setMaximumSize(new java.awt.Dimension(127, 180));
        button34.setMinimumSize(new java.awt.Dimension(127, 180));
        button34.setPreferredSize(new java.awt.Dimension(127, 180));
        button34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button34ActionPerformed(evt);
            }
        });
        getContentPane().add(button34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, -1, -1));

        button35.setMaximumSize(new java.awt.Dimension(127, 180));
        button35.setMinimumSize(new java.awt.Dimension(127, 180));
        button35.setPreferredSize(new java.awt.Dimension(127, 180));
        button35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button35ActionPerformed(evt);
            }
        });
        getContentPane().add(button35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 680, -1, -1));

        button36.setMaximumSize(new java.awt.Dimension(127, 180));
        button36.setMinimumSize(new java.awt.Dimension(127, 180));
        button36.setPreferredSize(new java.awt.Dimension(127, 180));
        button36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button36ActionPerformed(evt);
            }
        });
        getContentPane().add(button36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 680, -1, -1));

        button37.setMaximumSize(new java.awt.Dimension(127, 180));
        button37.setMinimumSize(new java.awt.Dimension(127, 180));
        button37.setPreferredSize(new java.awt.Dimension(127, 180));
        button37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button37ActionPerformed(evt);
            }
        });
        getContentPane().add(button37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 680, -1, -1));

        button38.setMaximumSize(new java.awt.Dimension(127, 180));
        button38.setMinimumSize(new java.awt.Dimension(127, 180));
        button38.setPreferredSize(new java.awt.Dimension(127, 180));
        button38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button38ActionPerformed(evt);
            }
        });
        getContentPane().add(button38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 680, -1, -1));

        button39.setMaximumSize(new java.awt.Dimension(127, 180));
        button39.setMinimumSize(new java.awt.Dimension(127, 180));
        button39.setPreferredSize(new java.awt.Dimension(127, 180));
        button39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button39ActionPerformed(evt);
            }
        });
        getContentPane().add(button39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 680, -1, -1));

        button27.setMaximumSize(new java.awt.Dimension(127, 180));
        button27.setMinimumSize(new java.awt.Dimension(127, 180));
        button27.setPreferredSize(new java.awt.Dimension(127, 180));
        button27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button27ActionPerformed(evt);
            }
        });
        getContentPane().add(button27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 680, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        tableBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Documents\\NetBeansProjects\\Gamer-Fish\\Gamer -Fish\\table.png")); // NOI18N
        tableBackground.setText("jLabel2");
        tableBackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        tableBackground.setMinimumSize(new java.awt.Dimension(1920, 1080));
        tableBackground.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(tableBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button10ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button12ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button13ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button15ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button16ActionPerformed

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button17ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button18ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button19ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button20ActionPerformed

    private void buton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buton21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button22ActionPerformed

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button23ActionPerformed

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button24ActionPerformed

    private void button25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button25ActionPerformed

    private void button26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button26ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button14ActionPerformed

    private void button28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button28ActionPerformed

    private void button29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button29ActionPerformed

    private void button30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button30ActionPerformed

    private void button31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button31ActionPerformed

    private void button32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button32ActionPerformed

    private void button33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button33ActionPerformed

    private void button34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button34ActionPerformed

    private void button35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button35ActionPerformed

    private void button36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button36ActionPerformed

    private void button37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button37ActionPerformed

    private void button38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button38ActionPerformed

    private void button39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button39ActionPerformed

    private void button27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gameplay().setVisible(true);
            }
        });
        //playerHand [0][0] = button1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton buton21;
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button13;
    private javax.swing.JButton button14;
    private javax.swing.JButton button15;
    private javax.swing.JButton button16;
    private javax.swing.JButton button17;
    private javax.swing.JButton button18;
    private javax.swing.JButton button19;
    private javax.swing.JButton button2;
    private javax.swing.JButton button20;
    private javax.swing.JButton button22;
    private javax.swing.JButton button23;
    private javax.swing.JButton button24;
    private javax.swing.JButton button25;
    private javax.swing.JButton button26;
    private javax.swing.JButton button27;
    private javax.swing.JButton button28;
    private javax.swing.JButton button29;
    private javax.swing.JButton button3;
    private javax.swing.JButton button30;
    private javax.swing.JButton button31;
    private javax.swing.JButton button32;
    private javax.swing.JButton button33;
    private javax.swing.JButton button34;
    private javax.swing.JButton button35;
    private javax.swing.JButton button36;
    private javax.swing.JButton button37;
    private javax.swing.JButton button38;
    private javax.swing.JButton button39;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tableBackground;
    // End of variables declaration//GEN-END:variables
    //private javax.swing.JButton[] playerHand = new JButton[39];
}
